# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\workspace\SurvCalc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\workspace\SurvCalc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\workspace\SurvCalc\CMakeFiles C:\workspace\SurvCalc\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\workspace\SurvCalc\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SurvCalc

# Build rule for target.
SurvCalc: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 SurvCalc
.PHONY : SurvCalc

# fast build rule for target.
SurvCalc/fast:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/build
.PHONY : SurvCalc/fast

#=============================================================================
# Target rules for targets named icon

# Build rule for target.
icon: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 icon
.PHONY : icon

# fast build rule for target.
icon/fast:
	$(MAKE) -f CMakeFiles\icon.dir\build.make CMakeFiles/icon.dir/build
.PHONY : icon/fast

#=============================================================================
# Target rules for targets named version

# Build rule for target.
version: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 version
.PHONY : version

# fast build rule for target.
version/fast:
	$(MAKE) -f CMakeFiles\version.dir\build.make CMakeFiles/version.dir/build
.PHONY : version/fast

#=============================================================================
# Target rules for targets named newran

# Build rule for target.
newran: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 newran
.PHONY : newran

# fast build rule for target.
newran/fast:
	$(MAKE) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/build
.PHONY : newran/fast

# target to build an object file
src/betadiff/betadiff.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/betadiff/betadiff.obj
.PHONY : src/betadiff/betadiff.obj

# target to preprocess a source file
src/betadiff/betadiff.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/betadiff/betadiff.i
.PHONY : src/betadiff/betadiff.i

# target to generate assembly for a file
src/betadiff/betadiff.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/betadiff/betadiff.s
.PHONY : src/betadiff/betadiff.s

# target to build an object file
src/datamanager.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/datamanager.obj
.PHONY : src/datamanager.obj

# target to preprocess a source file
src/datamanager.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/datamanager.i
.PHONY : src/datamanager.i

# target to generate assembly for a file
src/datamanager.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/datamanager.s
.PHONY : src/datamanager.s

# target to build an object file
src/development.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/development.obj
.PHONY : src/development.obj

# target to preprocess a source file
src/development.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/development.i
.PHONY : src/development.i

# target to generate assembly for a file
src/development.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/development.s
.PHONY : src/development.s

# target to build an object file
src/dictionary.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/dictionary.obj
.PHONY : src/dictionary.obj

# target to preprocess a source file
src/dictionary.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/dictionary.i
.PHONY : src/dictionary.i

# target to generate assembly for a file
src/dictionary.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/dictionary.s
.PHONY : src/dictionary.s

# target to build an object file
src/model.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/model.obj
.PHONY : src/model.obj

# target to preprocess a source file
src/model.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/model.i
.PHONY : src/model.i

# target to generate assembly for a file
src/model.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/model.s
.PHONY : src/model.s

# target to build an object file
src/newran_02C/extreal.obj:
	$(MAKE) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/extreal.obj
.PHONY : src/newran_02C/extreal.obj

# target to preprocess a source file
src/newran_02C/extreal.i:
	$(MAKE) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/extreal.i
.PHONY : src/newran_02C/extreal.i

# target to generate assembly for a file
src/newran_02C/extreal.s:
	$(MAKE) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/extreal.s
.PHONY : src/newran_02C/extreal.s

# target to build an object file
src/newran_02C/myexcept.obj:
	$(MAKE) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/myexcept.obj
.PHONY : src/newran_02C/myexcept.obj

# target to preprocess a source file
src/newran_02C/myexcept.i:
	$(MAKE) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/myexcept.i
.PHONY : src/newran_02C/myexcept.i

# target to generate assembly for a file
src/newran_02C/myexcept.s:
	$(MAKE) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/myexcept.s
.PHONY : src/newran_02C/myexcept.s

# target to build an object file
src/newran_02C/newran.obj:
	$(MAKE) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/newran.obj
.PHONY : src/newran_02C/newran.obj

# target to preprocess a source file
src/newran_02C/newran.i:
	$(MAKE) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/newran.i
.PHONY : src/newran_02C/newran.i

# target to generate assembly for a file
src/newran_02C/newran.s:
	$(MAKE) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/newran.s
.PHONY : src/newran_02C/newran.s

# target to build an object file
src/parameter_set.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/parameter_set.obj
.PHONY : src/parameter_set.obj

# target to preprocess a source file
src/parameter_set.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/parameter_set.i
.PHONY : src/parameter_set.i

# target to generate assembly for a file
src/parameter_set.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/parameter_set.s
.PHONY : src/parameter_set.s

# target to build an object file
src/sample.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/sample.obj
.PHONY : src/sample.obj

# target to preprocess a source file
src/sample.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/sample.i
.PHONY : src/sample.i

# target to generate assembly for a file
src/sample.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/sample.s
.PHONY : src/sample.s

# target to build an object file
src/species.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/species.obj
.PHONY : src/species.obj

# target to preprocess a source file
src/species.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/species.i
.PHONY : src/species.i

# target to generate assembly for a file
src/species.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/species.s
.PHONY : src/species.s

# target to build an object file
src/station.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/station.obj
.PHONY : src/station.obj

# target to preprocess a source file
src/station.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/station.i
.PHONY : src/station.i

# target to generate assembly for a file
src/station.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/station.s
.PHONY : src/station.s

# target to build an object file
src/stratum.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/stratum.obj
.PHONY : src/stratum.obj

# target to preprocess a source file
src/stratum.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/stratum.i
.PHONY : src/stratum.i

# target to generate assembly for a file
src/stratum.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/stratum.s
.PHONY : src/stratum.s

# target to build an object file
src/survey.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/survey.obj
.PHONY : src/survey.obj

# target to preprocess a source file
src/survey.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/survey.i
.PHONY : src/survey.i

# target to generate assembly for a file
src/survey.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/survey.s
.PHONY : src/survey.s

# target to build an object file
src/t_LW_coeffs.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_LW_coeffs.obj
.PHONY : src/t_LW_coeffs.obj

# target to preprocess a source file
src/t_LW_coeffs.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_LW_coeffs.i
.PHONY : src/t_LW_coeffs.i

# target to generate assembly for a file
src/t_LW_coeffs.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_LW_coeffs.s
.PHONY : src/t_LW_coeffs.s

# target to build an object file
src/t_catch.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_catch.obj
.PHONY : src/t_catch.obj

# target to preprocess a source file
src/t_catch.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_catch.i
.PHONY : src/t_catch.i

# target to generate assembly for a file
src/t_catch.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_catch.s
.PHONY : src/t_catch.s

# target to build an object file
src/t_lgth.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_lgth.obj
.PHONY : src/t_lgth.obj

# target to preprocess a source file
src/t_lgth.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_lgth.i
.PHONY : src/t_lgth.i

# target to generate assembly for a file
src/t_lgth.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_lgth.s
.PHONY : src/t_lgth.s

# target to build an object file
src/t_station.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_station.obj
.PHONY : src/t_station.obj

# target to preprocess a source file
src/t_station.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_station.i
.PHONY : src/t_station.i

# target to generate assembly for a file
src/t_station.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_station.s
.PHONY : src/t_station.s

# target to build an object file
src/t_station_catch.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_station_catch.obj
.PHONY : src/t_station_catch.obj

# target to preprocess a source file
src/t_station_catch.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_station_catch.i
.PHONY : src/t_station_catch.i

# target to generate assembly for a file
src/t_station_catch.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_station_catch.s
.PHONY : src/t_station_catch.s

# target to build an object file
src/t_stratum.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_stratum.obj
.PHONY : src/t_stratum.obj

# target to preprocess a source file
src/t_stratum.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_stratum.i
.PHONY : src/t_stratum.i

# target to generate assembly for a file
src/t_stratum.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_stratum.s
.PHONY : src/t_stratum.s

# target to build an object file
src/t_stratum_catch.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_stratum_catch.obj
.PHONY : src/t_stratum_catch.obj

# target to preprocess a source file
src/t_stratum_catch.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_stratum_catch.i
.PHONY : src/t_stratum_catch.i

# target to generate assembly for a file
src/t_stratum_catch.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_stratum_catch.s
.PHONY : src/t_stratum_catch.s

# target to build an object file
src/t_subcatch.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_subcatch.obj
.PHONY : src/t_subcatch.obj

# target to preprocess a source file
src/t_subcatch.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_subcatch.i
.PHONY : src/t_subcatch.i

# target to generate assembly for a file
src/t_subcatch.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_subcatch.s
.PHONY : src/t_subcatch.s

# target to build an object file
src/trip.obj:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/trip.obj
.PHONY : src/trip.obj

# target to preprocess a source file
src/trip.i:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/trip.i
.PHONY : src/trip.i

# target to generate assembly for a file
src/trip.s:
	$(MAKE) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/trip.s
.PHONY : src/trip.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... SurvCalc
	@echo ... icon
	@echo ... version
	@echo ... newran
	@echo ... rebuild_cache
	@echo ... src/betadiff/betadiff.obj
	@echo ... src/betadiff/betadiff.i
	@echo ... src/betadiff/betadiff.s
	@echo ... src/datamanager.obj
	@echo ... src/datamanager.i
	@echo ... src/datamanager.s
	@echo ... src/development.obj
	@echo ... src/development.i
	@echo ... src/development.s
	@echo ... src/dictionary.obj
	@echo ... src/dictionary.i
	@echo ... src/dictionary.s
	@echo ... src/model.obj
	@echo ... src/model.i
	@echo ... src/model.s
	@echo ... src/newran_02C/extreal.obj
	@echo ... src/newran_02C/extreal.i
	@echo ... src/newran_02C/extreal.s
	@echo ... src/newran_02C/myexcept.obj
	@echo ... src/newran_02C/myexcept.i
	@echo ... src/newran_02C/myexcept.s
	@echo ... src/newran_02C/newran.obj
	@echo ... src/newran_02C/newran.i
	@echo ... src/newran_02C/newran.s
	@echo ... src/parameter_set.obj
	@echo ... src/parameter_set.i
	@echo ... src/parameter_set.s
	@echo ... src/sample.obj
	@echo ... src/sample.i
	@echo ... src/sample.s
	@echo ... src/species.obj
	@echo ... src/species.i
	@echo ... src/species.s
	@echo ... src/station.obj
	@echo ... src/station.i
	@echo ... src/station.s
	@echo ... src/stratum.obj
	@echo ... src/stratum.i
	@echo ... src/stratum.s
	@echo ... src/survey.obj
	@echo ... src/survey.i
	@echo ... src/survey.s
	@echo ... src/t_LW_coeffs.obj
	@echo ... src/t_LW_coeffs.i
	@echo ... src/t_LW_coeffs.s
	@echo ... src/t_catch.obj
	@echo ... src/t_catch.i
	@echo ... src/t_catch.s
	@echo ... src/t_lgth.obj
	@echo ... src/t_lgth.i
	@echo ... src/t_lgth.s
	@echo ... src/t_station.obj
	@echo ... src/t_station.i
	@echo ... src/t_station.s
	@echo ... src/t_station_catch.obj
	@echo ... src/t_station_catch.i
	@echo ... src/t_station_catch.s
	@echo ... src/t_stratum.obj
	@echo ... src/t_stratum.i
	@echo ... src/t_stratum.s
	@echo ... src/t_stratum_catch.obj
	@echo ... src/t_stratum_catch.i
	@echo ... src/t_stratum_catch.s
	@echo ... src/t_subcatch.obj
	@echo ... src/t_subcatch.i
	@echo ... src/t_subcatch.s
	@echo ... src/trip.obj
	@echo ... src/trip.i
	@echo ... src/trip.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

