# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\jyqal\OneDrive - Food and Agriculture Organization\workspace\SurvCalc"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\jyqal\OneDrive - Food and Agriculture Organization\workspace\SurvCalc"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\jyqal\OneDrive - Food and Agriculture Organization\workspace\SurvCalc\CMakeFiles" "C:\Users\jyqal\OneDrive - Food and Agriculture Organization\workspace\SurvCalc\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\jyqal\OneDrive - Food and Agriculture Organization\workspace\SurvCalc\CMakeFiles" 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\jyqal\OneDrive - Food and Agriculture Organization\workspace\SurvCalc\CMakeFiles" "C:\Users\jyqal\OneDrive - Food and Agriculture Organization\workspace\SurvCalc\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\jyqal\OneDrive - Food and Agriculture Organization\workspace\SurvCalc\CMakeFiles" 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named icon

# Build rule for target.
icon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 icon
.PHONY : icon

# fast build rule for target.
icon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\icon.dir\build.make CMakeFiles/icon.dir/build
.PHONY : icon/fast

#=============================================================================
# Target rules for targets named version

# Build rule for target.
version: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 version
.PHONY : version

# fast build rule for target.
version/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\version.dir\build.make CMakeFiles/version.dir/build
.PHONY : version/fast

#=============================================================================
# Target rules for targets named SurvCalc

# Build rule for target.
SurvCalc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 SurvCalc
.PHONY : SurvCalc

# fast build rule for target.
SurvCalc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/build
.PHONY : SurvCalc/fast

#=============================================================================
# Target rules for targets named newran

# Build rule for target.
newran: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 newran
.PHONY : newran

# fast build rule for target.
newran/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/build
.PHONY : newran/fast

src/betadiff/betadiff.obj: src/betadiff/betadiff.cpp.obj
.PHONY : src/betadiff/betadiff.obj

# target to build an object file
src/betadiff/betadiff.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/betadiff/betadiff.cpp.obj
.PHONY : src/betadiff/betadiff.cpp.obj

src/betadiff/betadiff.i: src/betadiff/betadiff.cpp.i
.PHONY : src/betadiff/betadiff.i

# target to preprocess a source file
src/betadiff/betadiff.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/betadiff/betadiff.cpp.i
.PHONY : src/betadiff/betadiff.cpp.i

src/betadiff/betadiff.s: src/betadiff/betadiff.cpp.s
.PHONY : src/betadiff/betadiff.s

# target to generate assembly for a file
src/betadiff/betadiff.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/betadiff/betadiff.cpp.s
.PHONY : src/betadiff/betadiff.cpp.s

src/datamanager.obj: src/datamanager.cpp.obj
.PHONY : src/datamanager.obj

# target to build an object file
src/datamanager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/datamanager.cpp.obj
.PHONY : src/datamanager.cpp.obj

src/datamanager.i: src/datamanager.cpp.i
.PHONY : src/datamanager.i

# target to preprocess a source file
src/datamanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/datamanager.cpp.i
.PHONY : src/datamanager.cpp.i

src/datamanager.s: src/datamanager.cpp.s
.PHONY : src/datamanager.s

# target to generate assembly for a file
src/datamanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/datamanager.cpp.s
.PHONY : src/datamanager.cpp.s

src/development.obj: src/development.cpp.obj
.PHONY : src/development.obj

# target to build an object file
src/development.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/development.cpp.obj
.PHONY : src/development.cpp.obj

src/development.i: src/development.cpp.i
.PHONY : src/development.i

# target to preprocess a source file
src/development.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/development.cpp.i
.PHONY : src/development.cpp.i

src/development.s: src/development.cpp.s
.PHONY : src/development.s

# target to generate assembly for a file
src/development.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/development.cpp.s
.PHONY : src/development.cpp.s

src/dictionary.obj: src/dictionary.cpp.obj
.PHONY : src/dictionary.obj

# target to build an object file
src/dictionary.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/dictionary.cpp.obj
.PHONY : src/dictionary.cpp.obj

src/dictionary.i: src/dictionary.cpp.i
.PHONY : src/dictionary.i

# target to preprocess a source file
src/dictionary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/dictionary.cpp.i
.PHONY : src/dictionary.cpp.i

src/dictionary.s: src/dictionary.cpp.s
.PHONY : src/dictionary.s

# target to generate assembly for a file
src/dictionary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/dictionary.cpp.s
.PHONY : src/dictionary.cpp.s

src/model.obj: src/model.cpp.obj
.PHONY : src/model.obj

# target to build an object file
src/model.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/model.cpp.obj
.PHONY : src/model.cpp.obj

src/model.i: src/model.cpp.i
.PHONY : src/model.i

# target to preprocess a source file
src/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/model.cpp.i
.PHONY : src/model.cpp.i

src/model.s: src/model.cpp.s
.PHONY : src/model.s

# target to generate assembly for a file
src/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/model.cpp.s
.PHONY : src/model.cpp.s

src/newran_02C/extreal.obj: src/newran_02C/extreal.cpp.obj
.PHONY : src/newran_02C/extreal.obj

# target to build an object file
src/newran_02C/extreal.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/extreal.cpp.obj
.PHONY : src/newran_02C/extreal.cpp.obj

src/newran_02C/extreal.i: src/newran_02C/extreal.cpp.i
.PHONY : src/newran_02C/extreal.i

# target to preprocess a source file
src/newran_02C/extreal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/extreal.cpp.i
.PHONY : src/newran_02C/extreal.cpp.i

src/newran_02C/extreal.s: src/newran_02C/extreal.cpp.s
.PHONY : src/newran_02C/extreal.s

# target to generate assembly for a file
src/newran_02C/extreal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/extreal.cpp.s
.PHONY : src/newran_02C/extreal.cpp.s

src/newran_02C/myexcept.obj: src/newran_02C/myexcept.cpp.obj
.PHONY : src/newran_02C/myexcept.obj

# target to build an object file
src/newran_02C/myexcept.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/myexcept.cpp.obj
.PHONY : src/newran_02C/myexcept.cpp.obj

src/newran_02C/myexcept.i: src/newran_02C/myexcept.cpp.i
.PHONY : src/newran_02C/myexcept.i

# target to preprocess a source file
src/newran_02C/myexcept.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/myexcept.cpp.i
.PHONY : src/newran_02C/myexcept.cpp.i

src/newran_02C/myexcept.s: src/newran_02C/myexcept.cpp.s
.PHONY : src/newran_02C/myexcept.s

# target to generate assembly for a file
src/newran_02C/myexcept.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/myexcept.cpp.s
.PHONY : src/newran_02C/myexcept.cpp.s

src/newran_02C/newran.obj: src/newran_02C/newran.cpp.obj
.PHONY : src/newran_02C/newran.obj

# target to build an object file
src/newran_02C/newran.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/newran.cpp.obj
.PHONY : src/newran_02C/newran.cpp.obj

src/newran_02C/newran.i: src/newran_02C/newran.cpp.i
.PHONY : src/newran_02C/newran.i

# target to preprocess a source file
src/newran_02C/newran.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/newran.cpp.i
.PHONY : src/newran_02C/newran.cpp.i

src/newran_02C/newran.s: src/newran_02C/newran.cpp.s
.PHONY : src/newran_02C/newran.s

# target to generate assembly for a file
src/newran_02C/newran.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\newran.dir\build.make CMakeFiles/newran.dir/src/newran_02C/newran.cpp.s
.PHONY : src/newran_02C/newran.cpp.s

src/parameter_set.obj: src/parameter_set.cpp.obj
.PHONY : src/parameter_set.obj

# target to build an object file
src/parameter_set.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/parameter_set.cpp.obj
.PHONY : src/parameter_set.cpp.obj

src/parameter_set.i: src/parameter_set.cpp.i
.PHONY : src/parameter_set.i

# target to preprocess a source file
src/parameter_set.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/parameter_set.cpp.i
.PHONY : src/parameter_set.cpp.i

src/parameter_set.s: src/parameter_set.cpp.s
.PHONY : src/parameter_set.s

# target to generate assembly for a file
src/parameter_set.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/parameter_set.cpp.s
.PHONY : src/parameter_set.cpp.s

src/sample.obj: src/sample.cpp.obj
.PHONY : src/sample.obj

# target to build an object file
src/sample.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/sample.cpp.obj
.PHONY : src/sample.cpp.obj

src/sample.i: src/sample.cpp.i
.PHONY : src/sample.i

# target to preprocess a source file
src/sample.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/sample.cpp.i
.PHONY : src/sample.cpp.i

src/sample.s: src/sample.cpp.s
.PHONY : src/sample.s

# target to generate assembly for a file
src/sample.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/sample.cpp.s
.PHONY : src/sample.cpp.s

src/species.obj: src/species.cpp.obj
.PHONY : src/species.obj

# target to build an object file
src/species.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/species.cpp.obj
.PHONY : src/species.cpp.obj

src/species.i: src/species.cpp.i
.PHONY : src/species.i

# target to preprocess a source file
src/species.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/species.cpp.i
.PHONY : src/species.cpp.i

src/species.s: src/species.cpp.s
.PHONY : src/species.s

# target to generate assembly for a file
src/species.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/species.cpp.s
.PHONY : src/species.cpp.s

src/station.obj: src/station.cpp.obj
.PHONY : src/station.obj

# target to build an object file
src/station.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/station.cpp.obj
.PHONY : src/station.cpp.obj

src/station.i: src/station.cpp.i
.PHONY : src/station.i

# target to preprocess a source file
src/station.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/station.cpp.i
.PHONY : src/station.cpp.i

src/station.s: src/station.cpp.s
.PHONY : src/station.s

# target to generate assembly for a file
src/station.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/station.cpp.s
.PHONY : src/station.cpp.s

src/stratum.obj: src/stratum.cpp.obj
.PHONY : src/stratum.obj

# target to build an object file
src/stratum.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/stratum.cpp.obj
.PHONY : src/stratum.cpp.obj

src/stratum.i: src/stratum.cpp.i
.PHONY : src/stratum.i

# target to preprocess a source file
src/stratum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/stratum.cpp.i
.PHONY : src/stratum.cpp.i

src/stratum.s: src/stratum.cpp.s
.PHONY : src/stratum.s

# target to generate assembly for a file
src/stratum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/stratum.cpp.s
.PHONY : src/stratum.cpp.s

src/survey.obj: src/survey.cpp.obj
.PHONY : src/survey.obj

# target to build an object file
src/survey.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/survey.cpp.obj
.PHONY : src/survey.cpp.obj

src/survey.i: src/survey.cpp.i
.PHONY : src/survey.i

# target to preprocess a source file
src/survey.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/survey.cpp.i
.PHONY : src/survey.cpp.i

src/survey.s: src/survey.cpp.s
.PHONY : src/survey.s

# target to generate assembly for a file
src/survey.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/survey.cpp.s
.PHONY : src/survey.cpp.s

src/t_LW_coeffs.obj: src/t_LW_coeffs.cpp.obj
.PHONY : src/t_LW_coeffs.obj

# target to build an object file
src/t_LW_coeffs.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_LW_coeffs.cpp.obj
.PHONY : src/t_LW_coeffs.cpp.obj

src/t_LW_coeffs.i: src/t_LW_coeffs.cpp.i
.PHONY : src/t_LW_coeffs.i

# target to preprocess a source file
src/t_LW_coeffs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_LW_coeffs.cpp.i
.PHONY : src/t_LW_coeffs.cpp.i

src/t_LW_coeffs.s: src/t_LW_coeffs.cpp.s
.PHONY : src/t_LW_coeffs.s

# target to generate assembly for a file
src/t_LW_coeffs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_LW_coeffs.cpp.s
.PHONY : src/t_LW_coeffs.cpp.s

src/t_catch.obj: src/t_catch.cpp.obj
.PHONY : src/t_catch.obj

# target to build an object file
src/t_catch.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_catch.cpp.obj
.PHONY : src/t_catch.cpp.obj

src/t_catch.i: src/t_catch.cpp.i
.PHONY : src/t_catch.i

# target to preprocess a source file
src/t_catch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_catch.cpp.i
.PHONY : src/t_catch.cpp.i

src/t_catch.s: src/t_catch.cpp.s
.PHONY : src/t_catch.s

# target to generate assembly for a file
src/t_catch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_catch.cpp.s
.PHONY : src/t_catch.cpp.s

src/t_lgth.obj: src/t_lgth.cpp.obj
.PHONY : src/t_lgth.obj

# target to build an object file
src/t_lgth.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_lgth.cpp.obj
.PHONY : src/t_lgth.cpp.obj

src/t_lgth.i: src/t_lgth.cpp.i
.PHONY : src/t_lgth.i

# target to preprocess a source file
src/t_lgth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_lgth.cpp.i
.PHONY : src/t_lgth.cpp.i

src/t_lgth.s: src/t_lgth.cpp.s
.PHONY : src/t_lgth.s

# target to generate assembly for a file
src/t_lgth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_lgth.cpp.s
.PHONY : src/t_lgth.cpp.s

src/t_station.obj: src/t_station.cpp.obj
.PHONY : src/t_station.obj

# target to build an object file
src/t_station.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_station.cpp.obj
.PHONY : src/t_station.cpp.obj

src/t_station.i: src/t_station.cpp.i
.PHONY : src/t_station.i

# target to preprocess a source file
src/t_station.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_station.cpp.i
.PHONY : src/t_station.cpp.i

src/t_station.s: src/t_station.cpp.s
.PHONY : src/t_station.s

# target to generate assembly for a file
src/t_station.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_station.cpp.s
.PHONY : src/t_station.cpp.s

src/t_station_catch.obj: src/t_station_catch.cpp.obj
.PHONY : src/t_station_catch.obj

# target to build an object file
src/t_station_catch.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_station_catch.cpp.obj
.PHONY : src/t_station_catch.cpp.obj

src/t_station_catch.i: src/t_station_catch.cpp.i
.PHONY : src/t_station_catch.i

# target to preprocess a source file
src/t_station_catch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_station_catch.cpp.i
.PHONY : src/t_station_catch.cpp.i

src/t_station_catch.s: src/t_station_catch.cpp.s
.PHONY : src/t_station_catch.s

# target to generate assembly for a file
src/t_station_catch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_station_catch.cpp.s
.PHONY : src/t_station_catch.cpp.s

src/t_stratum.obj: src/t_stratum.cpp.obj
.PHONY : src/t_stratum.obj

# target to build an object file
src/t_stratum.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_stratum.cpp.obj
.PHONY : src/t_stratum.cpp.obj

src/t_stratum.i: src/t_stratum.cpp.i
.PHONY : src/t_stratum.i

# target to preprocess a source file
src/t_stratum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_stratum.cpp.i
.PHONY : src/t_stratum.cpp.i

src/t_stratum.s: src/t_stratum.cpp.s
.PHONY : src/t_stratum.s

# target to generate assembly for a file
src/t_stratum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_stratum.cpp.s
.PHONY : src/t_stratum.cpp.s

src/t_stratum_catch.obj: src/t_stratum_catch.cpp.obj
.PHONY : src/t_stratum_catch.obj

# target to build an object file
src/t_stratum_catch.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_stratum_catch.cpp.obj
.PHONY : src/t_stratum_catch.cpp.obj

src/t_stratum_catch.i: src/t_stratum_catch.cpp.i
.PHONY : src/t_stratum_catch.i

# target to preprocess a source file
src/t_stratum_catch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_stratum_catch.cpp.i
.PHONY : src/t_stratum_catch.cpp.i

src/t_stratum_catch.s: src/t_stratum_catch.cpp.s
.PHONY : src/t_stratum_catch.s

# target to generate assembly for a file
src/t_stratum_catch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_stratum_catch.cpp.s
.PHONY : src/t_stratum_catch.cpp.s

src/t_subcatch.obj: src/t_subcatch.cpp.obj
.PHONY : src/t_subcatch.obj

# target to build an object file
src/t_subcatch.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_subcatch.cpp.obj
.PHONY : src/t_subcatch.cpp.obj

src/t_subcatch.i: src/t_subcatch.cpp.i
.PHONY : src/t_subcatch.i

# target to preprocess a source file
src/t_subcatch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_subcatch.cpp.i
.PHONY : src/t_subcatch.cpp.i

src/t_subcatch.s: src/t_subcatch.cpp.s
.PHONY : src/t_subcatch.s

# target to generate assembly for a file
src/t_subcatch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/t_subcatch.cpp.s
.PHONY : src/t_subcatch.cpp.s

src/trip.obj: src/trip.cpp.obj
.PHONY : src/trip.obj

# target to build an object file
src/trip.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/trip.cpp.obj
.PHONY : src/trip.cpp.obj

src/trip.i: src/trip.cpp.i
.PHONY : src/trip.i

# target to preprocess a source file
src/trip.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/trip.cpp.i
.PHONY : src/trip.cpp.i

src/trip.s: src/trip.cpp.s
.PHONY : src/trip.s

# target to generate assembly for a file
src/trip.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SurvCalc.dir\build.make CMakeFiles/SurvCalc.dir/src/trip.cpp.s
.PHONY : src/trip.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... codegen
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... icon
	@echo ... version
	@echo ... SurvCalc
	@echo ... newran
	@echo ... src/betadiff/betadiff.obj
	@echo ... src/betadiff/betadiff.i
	@echo ... src/betadiff/betadiff.s
	@echo ... src/datamanager.obj
	@echo ... src/datamanager.i
	@echo ... src/datamanager.s
	@echo ... src/development.obj
	@echo ... src/development.i
	@echo ... src/development.s
	@echo ... src/dictionary.obj
	@echo ... src/dictionary.i
	@echo ... src/dictionary.s
	@echo ... src/model.obj
	@echo ... src/model.i
	@echo ... src/model.s
	@echo ... src/newran_02C/extreal.obj
	@echo ... src/newran_02C/extreal.i
	@echo ... src/newran_02C/extreal.s
	@echo ... src/newran_02C/myexcept.obj
	@echo ... src/newran_02C/myexcept.i
	@echo ... src/newran_02C/myexcept.s
	@echo ... src/newran_02C/newran.obj
	@echo ... src/newran_02C/newran.i
	@echo ... src/newran_02C/newran.s
	@echo ... src/parameter_set.obj
	@echo ... src/parameter_set.i
	@echo ... src/parameter_set.s
	@echo ... src/sample.obj
	@echo ... src/sample.i
	@echo ... src/sample.s
	@echo ... src/species.obj
	@echo ... src/species.i
	@echo ... src/species.s
	@echo ... src/station.obj
	@echo ... src/station.i
	@echo ... src/station.s
	@echo ... src/stratum.obj
	@echo ... src/stratum.i
	@echo ... src/stratum.s
	@echo ... src/survey.obj
	@echo ... src/survey.i
	@echo ... src/survey.s
	@echo ... src/t_LW_coeffs.obj
	@echo ... src/t_LW_coeffs.i
	@echo ... src/t_LW_coeffs.s
	@echo ... src/t_catch.obj
	@echo ... src/t_catch.i
	@echo ... src/t_catch.s
	@echo ... src/t_lgth.obj
	@echo ... src/t_lgth.i
	@echo ... src/t_lgth.s
	@echo ... src/t_station.obj
	@echo ... src/t_station.i
	@echo ... src/t_station.s
	@echo ... src/t_station_catch.obj
	@echo ... src/t_station_catch.i
	@echo ... src/t_station_catch.s
	@echo ... src/t_stratum.obj
	@echo ... src/t_stratum.i
	@echo ... src/t_stratum.s
	@echo ... src/t_stratum_catch.obj
	@echo ... src/t_stratum_catch.i
	@echo ... src/t_stratum_catch.s
	@echo ... src/t_subcatch.obj
	@echo ... src/t_subcatch.i
	@echo ... src/t_subcatch.s
	@echo ... src/trip.obj
	@echo ... src/trip.i
	@echo ... src/trip.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

