allocate <-
function(constraint = "cv", limit = 20, strata, data, trace = F, more.info = F
           )
  ## 27-7-08 Ported to R by C. Francis
  ## 7-5-03 Corrected bug which happens when there is a stratum with only one 
  ## non-zero catch (replaced if(min(is.na(resids)) == 1) by
  ## if(sum(!is.na(resids)) <2) )
  ## 
  ## 9-10-03 This is Brian Bull's function allocate (28/5/99) with correction 
  ## of a bug (changed "improvement <- strata[, "variance"]..." to
  ## "improvement <- strata[, "single.variance"]..." in one place) and 
  ## following changes to standard functions.
  ## 8-10-03 Chris Francis replaced calls to Brian's functions mean.bb, 
  ## var.bb, and sort.col.bb by standard S functions
  ## 
  ## This program allocates stations to strata so as to achieve a given
  ## c.v., or to minimise the c.v. with a fixed number of stations.  It
  ## does not consider phase 2 stations. Nor does it consider multiple age
  ## classes or multiple species.  A minimum number of stations must be set
  ## in each stratum.
  ## 
  ## The cv is calculated based on historical station data:
  ## 
  ## For each stratum, a mean catch rate is calculated as a (unweighted)
  ## average of the mean catch rates from each of the previous surveys in
  ## that stratum (by the current stratum boundary definitions!)
  ## 
  ## We then assume that the catch rates in that stratum, in the current
  ## year, are generated by multiplying the mean catch rate by a residual
  ## randomly chosen (with equal probabilities) from that stratum, where
  ## the residuals are calculated by dividing the catch rate at a station
  ## by the mean catch rate in that stratum in that survey. (still using
  ## current stratum boundaries).
  ## 
  ## However we don't actually generate catch rates - we just calculate
  ## their variance and use that to figure the optimal allocation. (by an
  ## iterative method - starting with the minimum number of stations and
  ## repeatedly adding one station wherever it will do the most good)
  ## 
  ## So, we produce an allocation which (under our assumptions about the
  ## catch rates) has a given cv. That doesn't mean, I might add, that the
  ## _estimated_ cv produced by sampling with that allocation will
  ## necessarily be equal to the intended target (even if our catch rate
  ## assumptions are right).
  ## 
  ## This method may be a bit dodgy if the historical data includes both
  ## changes in sampling effort _and_ changes in fish
  ## abundance/distribution.
  ## 
  ## 
  ## The inputs are 
  ## 
  ## constraint: "cv" if the minimum number of stations are to be allocated
  ##         to get a fixed cv, or 
  ##         "stations" if a set number of stations are to be allocated to 
  ## 	minimise the cv.
  ## 
  ## limit: if constraint = "cv", the cv (as %) that is to be achieved, 
  ##                "stations", the number of stations that are to be allocated.
  ## 
  ## strata: a dataframe with 4 columns named: 
  ##          "stratum" a label for the stratum
  ##          "area" area in km^2
  ##          "minimum" the minimum number of stations allowed in that stratum 
  ##          "maximum" the minimum number of stations allowed in that stratum 
  ## 
  ## data: a dataframe of historical station data with 3 columns named:
  ##        "stratum" the stratum label (under CURRENT strata boundary
  ##                  definitions!)
  ##        "survey" a label for the survey in which the station was taken
  ##        "catch" the catch in tons per km, tons per km^2 or however
  ## 
  ## trace: set to T if you want to see each iterative step
  ## 
  ## more.info: set to T for more detailed output
  ## 
  ## The output is a list of 3 elements:
  ##  $cv: the cv achieved (according to the model...)
  ##  $stations: the total number of stations
  ##  $allocation: a dataframe with 2 columns named:
  ##                "stratum" the stratum label
  ##                "stations" the number of stations.
  ##
  ## check inputs for some errors
{
  if(constraint != "cv" & constraint != "stations") {
    stop("constraint set wrong")
  }
  min.stations <- sum(strata[, "minimum"])
  if(constraint == "stations" & limit < min.stations) {
    stop("not enough stations allowed for minimum allocation")
  }
                                        #	strata <- sort.col.bb(strata, 1)
  strata <- strata[order(strata[, 1]),  ]
  if(any(is.na(tapply(data[, "catch"], data[, "stratum"], length)))) {
    stop("some strata have no historical stations")
  }
  if(min(c(limit, strata[, "minimum"], strata[, "area"])) <= 0) {
    stop("something is nonpositive that shouldn't be")
  }
  ## loop through strata to calculate mean catch rates, and variances of residuals
  strata <- cbind(strata, mean.cr=0,resid.var=0)
  for(count in 1:length(strata[, 1])) {
    stratum <- as.character(strata[count, 1])
    stratum.data <- data[as.character(data[, "stratum"]) == stratum,
                         c("survey", "catch")]
    mean.cr.by.survey <- tapply(stratum.data[, "catch"], as.factor(
                                                                   stratum.data[, "survey"]), mean)
    strata[count, "mean.cr"] <- mean(mean.cr.by.survey[!is.na(
                                                              mean.cr.by.survey)])
    resids <- rep(0, length(stratum.data[, 1]))
    for(count2 in 1:length(resids)) {
      resids[count2] <- stratum.data[count2, "catch"]/
        mean.cr.by.survey[as.character(stratum.data[
                                                    count2, "survey"])]
    }
    ##		if(min(is.na(resids)) == 1) {
    if(sum(!is.na(resids)) < 2) {
      strata[count, "resid.var"] <- 0	
      ## this fish has never (or only once) been caught in this stratum
    }
    else strata[count, "resid.var"] <- var(resids[!is.na(resids)])
  }
  ## calculate mean and variance of biomass estimates from single transects for each stratum 
  ## (down to a constant factor)
  strata$mean <- strata[, "mean.cr"] * strata[, "area"]
  strata$single.variance <- strata[, "resid.var"] * strata[, "mean"]^2	
  ## calculate variance of biomass estimates with minimum station allocation for each stratum
  strata$allocation <- strata[, "minimum"]
  strata$variance <- strata[, "single.variance"]/
    strata[,"allocation"]	# calculate overall sum, variance and cv
  estimate <- sum(strata[, "mean"])
  variance <- sum(strata[, "variance"])
  cv <- (100 * sqrt(variance))/estimate
  ## now loop through, adding stations, until requirements satisfied!
  no.stations <- min.stations
  while((constraint == "cv" & cv > limit) | (constraint == "stations" & 
           no.stations < limit)) {
    improvement <- strata[, "single.variance"]/(strata[, 
                                                       "allocation"] * (strata[, "allocation"] + 1))
    too.many <- T
    while(too.many) {
      add.to <- (improvement == max(improvement))
      if(strata[add.to, "allocation"] < strata[add.to, 
                                               "maximum"]) {
        too.many <- F
      }
      else {
        improvement[improvement == max(improvement)] <- 
          0
      }
    }
    strata[add.to, "allocation"] <- strata[add.to, "allocation"] + 
      1
    strata[add.to, "variance"] <- strata[add.to, "single.variance"]/
      strata[add.to, "allocation"]
    variance <- sum(strata[, "variance"])
    cv <- (100 * sqrt(variance))/estimate
    no.stations <- no.stations + 1
    if(trace) {
      print(strata)
    }
  }
  if(more.info & !trace) {
    print(strata)
  }
  ## prepare outputs
  output <- list()
  output$cv <- cv
  output$stations <- no.stations
  alloc <- data.frame(cbind(as.character(strata[, "stratum"]), strata[, 
                                                                      "allocation"]))
  names(alloc) <- c("stratum", "stations")
  output$allocation <- alloc
  output
}

